apiVersion: v1
kind: Namespace
metadata:
  name: test
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-d
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      type: hello-world
  template:
    metadata: 
      name: hello-world-p
      labels:
        type: hello-world
    spec:
      containers:
        - name: hello-world-c
          image: vad1mo/hello-world-rest
          ports:
            - containerPort: 5050
---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: test
  labels:
    type: hello-world-svc
spec:
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    type: hello-world
status:
  loadBalancer: {}

---  

apiVersion: v1
kind: Namespace
metadata:
  name: test2

---

apiVersion: v1 
kind: Pod
metadata:
  name: busy-pod2
  namespace: test2
  labels:
    tier: jumppod
spec:
  containers:      
    - name: busybox-2
      image: radial/busyboxplus:curl
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    