apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    Teir: Web
spec:
  containers:
    - name: web-pod
      image: nginx
      resources: {}
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    Teir: App
spec:
  containers:
    - name: app-pod
      image: nginx
      resources: {}
  restartPolicy: Always
status: {}
  
      
        

  
        
      