apiVersion: v1
kind: Namespace
metadata:
  name: ps-4

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-app-daemon-set
  namespace: ps-4
  labels:
    type: web-server-ds
spec:
  selector:
    matchLabels:
      type: web-server
  template:
    metadata:
      name: web-app
      namespace: ps-4
      labels:
        type: web-server
    spec:
      containers:
        - name: web-app
          image: nginx
          # ports:
          #   - containerPort: 80
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
