apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b-100mi
spec: {}
status: {}

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-b-100mi
  namespace: tenant-b-100mi
spec:
  hard:
    requests.memory: 100Mi
    # limits.memory: 100Mi


---

apiVersion: v1
kind: Pod
metadata:
  name: tenant-b-100mi
  namespace: tenant-b-100mi
spec:
  containers:
    - name: tenant-b-100mi
      image: nginx
      resources:
        limits:
          # memory: "150Mi"
        requests:
          memory: "150Mi"
      