apiVersion: v1
kind: Namespace
metadata:
  name: rbac-test

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-test-sa
  namespace: rbac-test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-test-role
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ""
    resources:
      - pods

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-test-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-test-role
subjects:
  - kind: ServiceAccount
    name: rbac-test-sa
    namespace: rbac-test

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    run: nginx
spec:
  serviceAccountName: rbac-test-sa
  securityContext:
    runAsUser: 900
  containers:
    - name: test-pod-c
      image: nginx
      resources: {}        
  dnsPolicy: ClusterFirst
  restartPolicy: Always

