apiVersion: v1
kind: Namespace
metadata: 
  name: ps-5
  labels:
    name: ps-5

---

apiVersion: v1 
kind: Pod
metadata:
  name: web-server
  namespace: ps-5
  labels:
    tier: frontend
spec:
  containers:
    - name: web-server-container
      image: nginx
      ports:
        - containerPort: 80

---       

apiVersion: v1 
kind: Pod
metadata:
  name: busy-pod1
  namespace: ps-5
  labels:
    tier: jumppod
spec:
  containers:           
    - name: busybox-1
      image: radial/busyboxplus:curl
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]

---      

apiVersion: v1 
kind: Pod
metadata:
  name: busy-pod2
  namespace: ps-5
  labels:
    tier: jumppod
spec:
  containers:      
    - name: busybox-2
      image: radial/busyboxplus:curl
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
        

---

# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-ingress
#   namespace: ps-5
# spec:
#   podSelector:
#     matchLabels:
#       tier: test
#   policyTypes:
#   - Ingress
          
        
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
  namespace: ps-5
spec:
  podSelector:
    matchLabels:
      tier: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: jumppod
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          tier: jumppod
    ports:
    - protocol: TCP
      port: 80