apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata: 
  name: priviledged
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"
  hostPorts:
    - max: 0
      min: 65535
  privileged: true
  hostNetwork: true
  hostIPC: true
  hostPID: true

---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata: 
  name: restricted
spec:
  privileged: false
  hostNetwork: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostPID: false
  hostIPC: false
  hostPorts:
    - max: 443
      min: 443
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny    
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'configMap'
    - 'downwardAPI'
    - 'emptyDir'
    - 'persistentVolumeClaim'
    - 'secret'
    - 'projected'
  allowedCapabilities:
    - '*'
  
  
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        allowPrivilegeEscalation: true
