apiVersion: v1
kind: Pod
metadata:
  name: nginx-600
spec:
  containers:
  - name: cont
    image: nginx
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 600