apiVersion: v1
kind: Namespace
metadata:
  name: ps-8

---  

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-pvc
  namespace: ps-8
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  # volumeName: gke-pv
  resources:
    requests:
      storage: 500Mi
