apiVersion: v1
kind: Namespace
metadata:
  name: ps-8

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-pv
  namespace: ps-8
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/my-pv

##Can we create PV specific to namespace??    