apiVersion: v1
kind: Namespace
metadata:
  name: ps-3
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deploy
  namespace: ps-3
  labels:
    type: web-server-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web-server
  template:
    metadata:
      labels: 
        type: web-server
    spec:
      containers:
        - name: nginx-server
          image: nginx 
          ports:
            - containerPort: 80  
status:
  replicas: 3

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: ps-3
  labels:
    type: web-server-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    type: web-server
  type: LoadBalancer


