apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: perl-app
  name: perl-app
spec:
  containers:
  - image: perl
    name: perl-app
    command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}