apiVersion: v1
kind: Namespace
metadata:
  name: ps-2

---

apiVersion: v1
kind: Pod
metadata:
  name: set-env
  namespace: ps-2
spec:
  containers:
    - name: set-env
      image: nginx
      env:
        - name: Variable1
          value: somevalue
        - name: Variable2
          value: someothervalue