apiVersion: v1
kind: Namespace
metadata:
  name: ps-7

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ps-7
spec:
  replicas: 2
  minReadySeconds: 50
  strategy:
    rollingUpdate:
      maxSurge: 1        
  selector:
    matchLabels:
      type: web-server
  template:
    metadata:
      labels:
        type: web-server
    spec:
      containers:
        - name: nginx-webserver
          image: nginx
          ports:
            - containerPort: 80
          imagePullPolicy: Always
status:
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: ps-7
spec:
  selector:
    type: web-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
    